### ISSUE TITLE
Android older version support?

### ISSUE THREAD

**Issue by llgoer** [adnathan/ace#20]
ex. Android 4.0

**Comment by adnathan** [comment]
Right now 4.4 and later is supported, but I'll use this issue to track broadening the support. Thanks!

**Comment by ddouble** [comment]
>= 4.0 request support

**Comment by krik** [comment]
Baseline around 4.1. or 4.2 would help a lot!

**Comment by ztl8702** [comment]
Yeah. Android Jellybean is still popular （some 20% market share). http://developer.android.com/about/dashboards/index.html
@adnathan what are the major difficulties to support Android 4.0? Is it an API that does not exist?

**Comment by frederikbosch** [comment]
It would be my suggestion to have a `isSupported` method on the `window.ace` object. Then developers can upgrade devices that have support for ace to a more native ui while unsupported devices only have the web ui. In web development terms this is called `progressive enhancement`. I would love to see that instead of blocking access of a device to the app.

**Comment by frederikbosch** [comment]
Actually, I will try to add this feature in the next days via a PR.

**Comment by frederikbosch** [comment]
My new PR #41 brings a method called `isSupported` to the `window.ace` as described in my first reply. Now you can upgrade/enhance devices that support ace.
