### ISSUE TITLE
App is not responsive

### ISSUE THREAD

**Issue by subhashisrouth** [adnathan/ace#28]
```
<!DOCTYPE html>
<html>
<head>
   <title>Page Title</title>
</head>

<body onload="xx();">
   <p>Hello</p>
    <script type="text/javascript" src="cordova.js"></script>

    <script type="text/javascript">

         function xx(){
            document.addEventListener("deviceready", onDeviceReady, false);
         }

         function onDeviceReady(){

         ace.load("native://app.xaml", function (page) {
                  ace.getHostPage().setContent(page);
                  page.setContent(ace.getHostWebView());      
                  });

         }   
        </script>
</body>
</html>
```

Above is my simple html. I am using app.xmal from example folder, which is native tab bar. it shows the page with native tabbar, but it is unresponsive ( i.e. can't scroll up down ). Why?
![simulator screen shot 06-apr-2016 11 45 15 pm](https://cloud.githubusercontent.com/assets/6926322/14327832/a701179c-fc51-11e5-9c9c-57408c8ecb40.png)

**Comment by axemclion** [comment]
@subhashisrouth Is there you project uploaded somewhere so that we can take a look ?

**Comment by jmatthiesen** [comment]
Closing, since we haven't heard back for several months. Also, please note that we're no longer maintaining this repo. Here's the official notice, copied from our readme:

As of December 2016, this project is no longer maintained by Microsoft. We built ACE to provide developers with an “escape hatch” to access native code from within JavaScript. After nearly a year in production, we learned that most developers are satisfied with the access granted by Cordova’s Plugin Model. Thus, we’ve discontinued active development. We appreciate your interest in the project and hope you found it exemplary of Microsoft’s commitment to experimentation and open source software. if you're interested in continuing this project, please feel free to fork it. As of December 2016, we will no longer monitor or respond to open issues. You can keep up with other projects from Microsoft’s Cordova team by visiting http://taco.visualstudio.com. Thanks for your support!
