### ISSUE TITLE
Accessing cordova object or activity in android

### ISSUE THREAD

**Issue by dested** [adnathan/ace#29]
How would I go about accessing the cordova object that is typically provided when you create a cordova plugin? Is there any way to access that or the running activity via native android code?

Semi unrelated, but is the native code executed on its own thread or the UI thread?

**Comment by adnathan** [comment]
The CordovaPlugin object is ace.run.NativeHost, which exposes some static members for getting the main CordovaActivity, Application, root View, root Menu, and Intent (plus some other helpers). Would you find it useful to have a method that returns an instance of the CordovaPlugin object itself? I can certainly add that.

When your code is invoked on behalf of the Ace plugin, it is done on the UI thread.  That's because most scenarios have been for UI.  We could add a mechanism to opt out of that (or you can write a plugin as you would today without Ace).  Thanks!
