### ISSUE TITLE
Not supported on KitKat (4.4)

### ISSUE THREAD

**Issue by CodeMooseUS** [adnathan/ace#9]
Trying to deploy the AceExamples project against the VS emulator running KitKat (4.4) causes an error when you click any of the example links.

Here is the error when you click on the tabbar example:

I/chromium( 1338): [INFO:CONSOLE(310)] "Error in Error callbackId: NativeHost1222076338 : Error: Native error: java.lang.RuntimeException: Unable to find a class named 'run.ace.TabBar'
I/chromium( 1338):  at run.ace.IncomingMessages.create(IncomingMessages.java:49)
I/chromium( 1338):  at run.ace.NativeHost$2.run(NativeHost.java:223)
I/chromium( 1338):  at android.os.Handler.handleCallback(Handler.java:733)
I/chromium( 1338):  at android.os.Handler.dispatchMessage(Handler.java:95)
I/chromium( 1338):  at android.os.Looper.loop(Looper.java:136)
I/chromium( 1338):  at android.app.ActivityThread.main(ActivityThread.java:5001)
I/chromium( 1338):  at java.lang.reflect.Method.invokeNative(Native Method)
I/chromium( 1338):  at java.lang.reflect.Method.invoke(Method.java:515)
I/chromium( 1338):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
I/chromium( 1338):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
I/chromium( 1338):  at dalvik.system.NativeStart.main(Native Method)

**Comment by adnathan** [comment]
Thanks so much for reporting this!  With https://github.com/Microsoft/ace/commit/c85ba8ac40af090857f90e73bce731fe4629d508, I added Android version detection to at least alert the developer about what is going on instead of producing the unhelpful error you ran into.  I also updated the README and [getting started page on the website](http://microsoft.github.io/ace/docs/getting-started/) to mention Android version requirements.

That said, code changes should be made to enable Ace to work on KitKit.  (At least one problematic API in use is setBackgroundTintList.)  So I've left this issue open and marked it as a feature request.

**Comment by txchen** [comment]
I tried the AceExample and it cannot work on my 4.4.2 device.
KitKat is important, please support it. Thanks!

**Comment by adnathan** [comment]
Okay, with https://github.com/Microsoft/ace/commit/ae91c671fa48b937017aa65162d671961def84dd, https://github.com/Microsoft/ace/commit/ec4e4c77a89949bf40fa533b15e5a0ef72730483, and https://github.com/Microsoft/ace/commit/b86f0d8ef8767c56643a71919fa4ebe680d678ce, there are now no known issues with Ace or AceExamples on KitKat. If you find a problem, please file an issue. Thank you so much for your feedback!
